using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Flow.Launcher.Plugin.LoremIpsumGenerator.Classes
{
    public static class LoremWords
    {
        public static string[] Words =
        {
            "laborum",
            "eveniet",
            "sunt",
            "iure",
            "nobis",
            "odio",
            "quasi",
            "aut",
            "vel",
            "odit",
            "tempore",
            "facilis",
            "neque",
            "nihil",
            "vitae",
            "vero",
            "ipsum",
            "nisi",
            "animi",
            "cumque",
            "velit",
            "modi",
            "natus",
            "iusto",
            "illo",
            "sed",
            "tempora",
            "ratione",
            "rem",
            "sint",
            "unde",
            "qui",
            "amet",
            "quo",
            "culpa",
            "libero",
            "ipsa",
            "dicta",
            "nesciunt",
            "autem",
            "minima",
            "ipsam",
            "ullam",
            "totam",
            "quis",
            "dolores",
            "harum",
            "quia",
            "ea",
            "quas",
            "quam",
            "quae",
            "hic",
            "ut",
            "ad",
            "at",
            "in",
            "id",
            "quos",
            "sit",
            "eos",
            "alias",
            "dolore",
            "lorem",
            "ipsum",
            "dolor",
            "sit",
            "amet",
            "elit",
            "sed",
            "ut",
            "et"
        };
    }
}
